// Generated by npm run contract:build from contracts/RelayRegistry.sol.
export const registryAbi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "council_",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "catalogueId_",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "publisher_",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "topic_",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "checkpoint_",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "agreement_",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "CouncilOnly",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientThreshold",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidAppointment",
    type: "error",
  },
  {
    inputs: [],
    name: "StaleRevision",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "revision",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "previousPublisher",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "publisher",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "topic",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "checkpoint",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "agreement",
        type: "bytes32",
      },
    ],
    name: "StewardAppointed",
    type: "event",
  },
  {
    inputs: [],
    name: "agreement",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "expectedRevision",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "next",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "nextTopic",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "nextCheckpoint",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "nextAgreement",
        type: "bytes32",
      },
    ],
    name: "appoint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "catalogueId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "checkpoint",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "council",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "publisher",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "revision",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "topic",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
